INSERT INTO TBL_USERS ( ID, USERNAME, NAME, SURNAME, PASSWORD, CREATION_DATE, UPDATE_DATE ) VALUES ( 998, 'UserNoAccounts', 'UserNoAccounts', 'UserNoAccounts', '$2a$10$bsGtAktgumi4VFmAvX5N2ukoHpfWmlUEY0cFWm9Iv2mtqTuNLkgdG', '2025-10-12', '2025-10-12' );
INSERT INTO TBL_USERS ( ID, USERNAME, NAME, SURNAME, PASSWORD, CREATION_DATE, UPDATE_DATE ) VALUES ( 999, 'User', 'User', 'User', '$2a$10$bsGtAktgumi4VFmAvX5N2ukoHpfWmlUEY0cFWm9Iv2mtqTuNLkgdG', '2025-10-12', '2025-10-12' );

INSERT INTO TBL_ACCOUNTS (ID, ACCOUNT_NAME, CURRENCY, USER_ID) VALUES ( 998, 'Delete Account', 'EUR', 999 );
INSERT INTO TBL_ACCOUNTS (ID, ACCOUNT_NAME, CURRENCY, USER_ID) VALUES ( 999, 'Test Account', 'EUR', 999 );

INSERT INTO TBL_CATEGORIES (ID, USER_ID, CATEGORY_NAME) VALUES ( 991, 999, 'Loans' );
INSERT INTO TBL_CATEGORIES (ID, USER_ID, CATEGORY_NAME) VALUES ( 992, 999, 'Subscriptions' );
INSERT INTO TBL_CATEGORIES (ID, USER_ID, CATEGORY_NAME) VALUES ( 993, 999, 'Groceries' );
INSERT INTO TBL_CATEGORIES (ID, USER_ID, CATEGORY_NAME) VALUES ( 994, 999, 'Leisure' );
INSERT INTO TBL_CATEGORIES (ID, USER_ID, CATEGORY_NAME) VALUES ( 995, 999, 'Electronics' );
INSERT INTO TBL_CATEGORIES (ID, USER_ID, CATEGORY_NAME) VALUES ( 996, 999, 'Utilities' );
INSERT INTO TBL_CATEGORIES (ID, USER_ID, CATEGORY_NAME) VALUES ( 997, 999, 'Clothing' );
INSERT INTO TBL_CATEGORIES (ID, USER_ID, CATEGORY_NAME) VALUES ( 998, 999, 'Health' );
INSERT INTO TBL_CATEGORIES (ID, USER_ID, CATEGORY_NAME) VALUES ( 999, 999, 'Other' );

INSERT INTO TBL_MOVEMENTS (ID, ACCOUNT_ID, AMOUNT, CATEGORY_ID, COMMENT, DESTINATION_ACCOUNT_ID, EFFECTIVE_DATE) VALUES ( 995, 999, -12.99, 992, 'Netflix', NULL, '2025-05-10' );
INSERT INTO TBL_MOVEMENTS (ID, ACCOUNT_ID, AMOUNT, CATEGORY_ID, COMMENT, DESTINATION_ACCOUNT_ID, EFFECTIVE_DATE) VALUES ( 996, 999, -123.45, 991, 'Car Loan', NULL, '2025-07-23' );
INSERT INTO TBL_MOVEMENTS (ID, ACCOUNT_ID, AMOUNT, CATEGORY_ID, COMMENT, DESTINATION_ACCOUNT_ID, EFFECTIVE_DATE) VALUES ( 997, 999, -5.49, 994, 'Cinema', NULL, '2025-02-14' );
INSERT INTO TBL_MOVEMENTS (ID, ACCOUNT_ID, AMOUNT, CATEGORY_ID, COMMENT, DESTINATION_ACCOUNT_ID, EFFECTIVE_DATE) VALUES ( 998, 999, -43.75, 997, 'Pull&Bear', NULL, '2025-11-25' );
INSERT INTO TBL_MOVEMENTS (ID, ACCOUNT_ID, AMOUNT, CATEGORY_ID, COMMENT, DESTINATION_ACCOUNT_ID, EFFECTIVE_DATE) VALUES ( 999, 999, -14.32, 998, 'Cough drops', NULL, '2025-12-06' );