INSERT INTO TBL_USER( ID, USERNAME, NAME, SURNAME, PASSWORD, CREATION_DATE, UPDATE_DATE ) VALUES ( 998, 'UserNoAccounts', 'UserNoAccounts', 'UserNoAccounts', '$2a$10$bsGtAktgumi4VFmAvX5N2ukoHpfWmlUEY0cFWm9Iv2mtqTuNLkgdG', '2025-10-12', '2025-10-12' );
INSERT INTO TBL_USER( ID, USERNAME, NAME, SURNAME, PASSWORD, CREATION_DATE, UPDATE_DATE ) VALUES ( 999, 'User', 'User', 'User', '$2a$10$bsGtAktgumi4VFmAvX5N2ukoHpfWmlUEY0cFWm9Iv2mtqTuNLkgdG', '2025-10-12', '2025-10-12' );

INSERT INTO TBL_ACCOUNT (ID, ACCOUNT_NAME, CURRENCY, USER_ID) VALUES ( 998, 'Delete Account', 'EUR', 999 );
INSERT INTO TBL_ACCOUNT (ID, ACCOUNT_NAME, CURRENCY, USER_ID) VALUES ( 999, 'Test Account', 'EUR', 999 );